"""Unified client for OpenAI-compatible large language model APIs.

The module deliberately uses ``httpx`` instead of a provider SDK. Provider
selection is controlled by ``LLM_PROVIDER`` and defaults to ``deepseek``.
"""

from __future__ import annotations

import logging
import math
import os
import re
import time
from abc import ABC, abstractmethod
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from typing import Any

import httpx

LOGGER = logging.getLogger(__name__)

DEFAULT_TIMEOUT_SECONDS = 60.0
DEFAULT_RETRY_ATTEMPTS = 3
DEFAULT_RETRY_DELAY_SECONDS = 1.0

Message = Mapping[str, Any]


class LLMClientError(RuntimeError):
    """Base exception for LLM client failures."""


class LLMConfigurationError(LLMClientError):
    """Raised when provider configuration is incomplete or invalid."""


class LLMResponseError(LLMClientError):
    """Raised when a provider returns an unexpected response body."""


@dataclass(frozen=True)
class Usage:
    """Token usage for one LLM response.

    Attributes:
        prompt_tokens: Tokens consumed by input messages.
        completion_tokens: Tokens generated by the model.
        total_tokens: Sum of prompt and completion tokens.
        estimated: Whether the token counts were locally estimated.
    """

    prompt_tokens: int
    completion_tokens: int
    total_tokens: int
    estimated: bool = False


@dataclass(frozen=True)
class ModelPricing:
    """Model prices in USD per one million tokens.

    Attributes:
        input_per_million: Price for one million input tokens.
        output_per_million: Price for one million output tokens.
    """

    input_per_million: float
    output_per_million: float


@dataclass(frozen=True)
class LLMResponse:
    """Provider-independent LLM response.

    Attributes:
        content: Text returned by the model.
        usage: Prompt, completion, and total token counts.
        provider: Normalized provider name.
        model: Model identifier used for the request.
        estimated_cost_usd: Estimated request cost, if pricing is known.
    """

    content: str
    usage: Usage
    provider: str
    model: str
    estimated_cost_usd: float | None = None


@dataclass(frozen=True)
class ProviderConfig:
    """Static defaults for one API provider."""

    name: str
    base_url: str
    default_model: str
    api_key_variables: tuple[str, ...]
    base_url_variable: str
    model_variable: str
    max_tokens_field: str = "max_tokens"


PROVIDER_CONFIGS: dict[str, ProviderConfig] = {
    "chatgpt": ProviderConfig(
        name="chatgpt",
        base_url="https://api.openai.com/v1",
        default_model="gpt-5.4-mini",
        api_key_variables=("CHATGPT_API_KEY", "OPENAI_API_KEY"),
        base_url_variable="CHATGPT_BASE_URL",
        model_variable="CHATGPT_MODEL",
        max_tokens_field="max_completion_tokens",
    ),
    "openai": ProviderConfig(
        name="openai",
        base_url="https://api.openai.com/v1",
        default_model="gpt-5.4-mini",
        api_key_variables=("OPENAI_API_KEY",),
        base_url_variable="OPENAI_BASE_URL",
        model_variable="OPENAI_MODEL",
        max_tokens_field="max_completion_tokens",
    ),
    "deepseek": ProviderConfig(
        name="deepseek",
        base_url="https://api.deepseek.com",
        default_model="deepseek-v4-flash",
        api_key_variables=("DEEPSEEK_API_KEY",),
        base_url_variable="DEEPSEEK_BASE_URL",
        model_variable="DEEPSEEK_MODEL",
    ),
    "qwen": ProviderConfig(
        name="qwen",
        base_url="https://dashscope.aliyuncs.com/compatible-mode/v1",
        default_model="qwen-plus",
        api_key_variables=("QWEN_API_KEY", "DASHSCOPE_API_KEY"),
        base_url_variable="QWEN_BASE_URL",
        model_variable="QWEN_MODEL",
    ),
}

# Prices are USD per one million tokens. Unknown models intentionally have no
# fallback price; set LLM_INPUT_COST_PER_MILLION and
# LLM_OUTPUT_COST_PER_MILLION when using one of them.
DEFAULT_PRICING: dict[tuple[str, str], ModelPricing] = {
    ("chatgpt", "gpt-5.4-mini"): ModelPricing(0.75, 4.50),
    ("openai", "gpt-5.4-mini"): ModelPricing(0.75, 4.50),
    ("deepseek", "deepseek-v4-flash"): ModelPricing(0.14, 0.28),
    ("deepseek", "deepseek-v4-pro"): ModelPricing(0.435, 0.87),
}

_CJK_PATTERN = re.compile(r"[\u3400-\u4dbf\u4e00-\u9fff\uf900-\ufaff]")


def estimate_tokens(text: str) -> int:
    """Estimate token count without a tokenizer dependency.

    CJK characters are approximated as one token each. Other characters are
    approximated as one token per four characters. This is intended for cost
    planning and as a fallback when an API omits usage data, not for enforcing
    exact context limits.

    Args:
        text: Text whose token count should be estimated.

    Returns:
        A non-negative approximate token count.
    """

    if not text:
        return 0
    cjk_count = len(_CJK_PATTERN.findall(text))
    non_cjk_count = len(text) - cjk_count
    return cjk_count + math.ceil(non_cjk_count / 4)


def estimate_message_tokens(messages: Sequence[Message]) -> int:
    """Estimate tokens used by chat messages.

    Args:
        messages: OpenAI-compatible chat messages.

    Returns:
        Approximate token count including lightweight message overhead.
    """

    token_count = 2
    for message in messages:
        token_count += 4
        token_count += estimate_tokens(str(message.get("role", "")))
        token_count += estimate_tokens(_content_to_text(message.get("content")))
    return token_count


def calculate_cost_usd(usage: Usage, pricing: ModelPricing) -> float:
    """Calculate an estimated cost in USD.

    Args:
        usage: Input and output token usage.
        pricing: USD prices per one million tokens.

    Returns:
        Estimated cost in USD.
    """

    input_cost = usage.prompt_tokens * pricing.input_per_million / 1_000_000
    output_cost = usage.completion_tokens * pricing.output_per_million / 1_000_000
    return input_cost + output_cost


class LLMProvider(ABC):
    """Abstract interface implemented by LLM providers."""

    @abstractmethod
    def chat(
        self,
        messages: Sequence[Message],
        *,
        temperature: float | None = None,
        max_tokens: int | None = None,
    ) -> LLMResponse:
        """Send a chat-completion request.

        Args:
            messages: Chat messages with ``role`` and ``content`` fields.
            temperature: Optional sampling temperature.
            max_tokens: Optional maximum number of output tokens.

        Returns:
            A provider-independent response.
        """


class OpenAICompatibleProvider(LLMProvider):
    """Client for an OpenAI-compatible chat-completions endpoint."""

    def __init__(
        self,
        *,
        provider_name: str,
        api_key: str,
        base_url: str,
        model: str,
        pricing: ModelPricing | None = None,
        timeout_seconds: float = DEFAULT_TIMEOUT_SECONDS,
        max_tokens_field: str = "max_tokens",
        transport: httpx.BaseTransport | None = None,
    ) -> None:
        """Initialize an OpenAI-compatible provider.

        Args:
            provider_name: Provider identifier used in responses and logs.
            api_key: Bearer token for the provider API.
            base_url: API base URL, optionally ending in ``/v1``.
            model: Model identifier sent with each request.
            pricing: Optional USD pricing used for cost estimation.
            timeout_seconds: Timeout applied to the entire HTTP operation.
            max_tokens_field: Provider-specific output-token field name.
            transport: Optional httpx transport, primarily for testing.

        Raises:
            LLMConfigurationError: If required values are missing.
        """

        if not api_key.strip():
            raise LLMConfigurationError("API key must not be empty")
        if not base_url.strip():
            raise LLMConfigurationError("API base URL must not be empty")
        if not model.strip():
            raise LLMConfigurationError("Model name must not be empty")
        if timeout_seconds <= 0:
            raise LLMConfigurationError("Timeout must be greater than zero")

        self.provider_name = provider_name
        self.api_key = api_key
        self.base_url = base_url.rstrip("/")
        self.model = model
        self.pricing = pricing
        self.timeout = httpx.Timeout(timeout_seconds)
        self.max_tokens_field = max_tokens_field
        self.transport = transport

    def chat(
        self,
        messages: Sequence[Message],
        *,
        temperature: float | None = None,
        max_tokens: int | None = None,
    ) -> LLMResponse:
        """Send a request to ``/chat/completions``.

        Args:
            messages: Chat messages with ``role`` and ``content`` fields.
            temperature: Optional sampling temperature.
            max_tokens: Optional maximum number of output tokens.

        Returns:
            Normalized content, usage, model, provider, and estimated cost.

        Raises:
            httpx.HTTPError: If the HTTP operation fails.
            LLMConfigurationError: If messages or options are invalid.
            LLMResponseError: If the response body is malformed.
        """

        _validate_messages(messages)
        if max_tokens is not None and max_tokens <= 0:
            raise LLMConfigurationError("max_tokens must be greater than zero")

        payload: dict[str, Any] = {
            "model": self.model,
            "messages": [dict(message) for message in messages],
        }
        if temperature is not None:
            payload["temperature"] = temperature
        if max_tokens is not None:
            payload[self.max_tokens_field] = max_tokens

        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }
        with httpx.Client(
            timeout=self.timeout,
            transport=self.transport,
        ) as client:
            response = client.post(
                f"{self.base_url}/chat/completions",
                headers=headers,
                json=payload,
            )
            response.raise_for_status()

        return self._parse_response(response, messages)

    def _parse_response(
        self,
        response: httpx.Response,
        messages: Sequence[Message],
    ) -> LLMResponse:
        """Normalize an OpenAI-compatible response body."""

        try:
            payload = response.json()
        except ValueError as error:
            raise LLMResponseError("Provider returned invalid JSON") from error

        if not isinstance(payload, Mapping):
            raise LLMResponseError("Provider response must be a JSON object")

        choices = payload.get("choices")
        if not isinstance(choices, list) or not choices:
            raise LLMResponseError("Provider response has no choices")
        first_choice = choices[0]
        if not isinstance(first_choice, Mapping):
            raise LLMResponseError("Provider returned an invalid choice")
        message = first_choice.get("message")
        if not isinstance(message, Mapping):
            raise LLMResponseError("Provider choice has no message")

        content = _content_to_text(message.get("content"))
        usage = _parse_usage(payload.get("usage"), messages, content)
        cost = calculate_cost_usd(usage, self.pricing) if self.pricing is not None else None
        response_model = payload.get("model")
        if not isinstance(response_model, str) or not response_model:
            response_model = self.model

        return LLMResponse(
            content=content,
            usage=usage,
            provider=self.provider_name,
            model=response_model,
            estimated_cost_usd=cost,
        )


def create_provider(provider_name: str | None = None) -> LLMProvider:
    """Create a provider from environment variables.

    Configuration priority is the generic ``LLM_*`` variable, followed by the
    provider-specific variable, followed by a built-in default where one is
    safe. For example, Qwen accepts ``LLM_API_KEY``, ``QWEN_API_KEY``, or
    ``DASHSCOPE_API_KEY``.

    Args:
        provider_name: Optional provider override. When omitted,
            ``LLM_PROVIDER`` is used and defaults to ``deepseek``.

    Returns:
        Configured OpenAI-compatible provider.

    Raises:
        LLMConfigurationError: If the provider is unknown or its key is absent.
    """

    selected_name = provider_name or os.getenv("LLM_PROVIDER", "deepseek")
    normalized_name = selected_name.strip().lower().replace("_", "")
    if normalized_name == "chatgpt":
        normalized_name = "chatgpt"

    config = PROVIDER_CONFIGS.get(normalized_name)
    if config is None:
        supported = ", ".join(sorted(PROVIDER_CONFIGS))
        raise LLMConfigurationError(
            f"Unsupported LLM provider {selected_name!r}; choose {supported}"
        )

    api_key = _first_environment_value(("LLM_API_KEY", *config.api_key_variables))
    if api_key is None:
        variables = ", ".join(("LLM_API_KEY", *config.api_key_variables))
        detail = ""
        if normalized_name == "chatgpt":
            detail = " A ChatGPT browser login is not an API credential; provide an OpenAI API key."
        raise LLMConfigurationError(f"Missing API key; set one of: {variables}.{detail}")

    base_url = os.getenv("LLM_BASE_URL") or os.getenv(config.base_url_variable) or config.base_url
    model = os.getenv("LLM_MODEL") or os.getenv(config.model_variable) or config.default_model
    pricing = _resolve_pricing(normalized_name, model)

    return OpenAICompatibleProvider(
        provider_name=config.name,
        api_key=api_key,
        base_url=base_url,
        model=model,
        pricing=pricing,
        timeout_seconds=DEFAULT_TIMEOUT_SECONDS,
        max_tokens_field=config.max_tokens_field,
    )


def chat_with_retry(
    provider: LLMProvider,
    messages: Sequence[Message],
    *,
    temperature: float | None = None,
    max_tokens: int | None = None,
    attempts: int = DEFAULT_RETRY_ATTEMPTS,
    initial_delay_seconds: float = DEFAULT_RETRY_DELAY_SECONDS,
) -> LLMResponse:
    """Call a provider with bounded exponential-backoff retries.

    Network/timeout errors, HTTP 429, and HTTP 5xx responses are retried. Other
    HTTP errors and invalid response bodies fail immediately.

    Args:
        provider: Provider that performs the chat request.
        messages: Chat messages with ``role`` and ``content`` fields.
        temperature: Optional sampling temperature.
        max_tokens: Optional maximum number of output tokens.
        attempts: Total number of attempts, including the first call.
        initial_delay_seconds: Delay before the first retry; subsequent delays
            double exponentially.

    Returns:
        The first successful response.

    Raises:
        ValueError: If retry settings are invalid.
        httpx.HTTPError: If all retryable attempts fail, or a non-retryable HTTP
            error occurs.
        LLMClientError: If configuration or response parsing fails.
    """

    if attempts < 1:
        raise ValueError("attempts must be at least one")
    if initial_delay_seconds < 0:
        raise ValueError("initial_delay_seconds must not be negative")

    for attempt in range(1, attempts + 1):
        try:
            return provider.chat(
                messages,
                temperature=temperature,
                max_tokens=max_tokens,
            )
        except httpx.HTTPStatusError as error:
            status_code = error.response.status_code
            retryable = status_code == 429 or status_code >= 500
            if not retryable or attempt == attempts:
                raise
            _log_retry(attempt, attempts, f"HTTP {status_code}")
        except httpx.TransportError as error:
            if attempt == attempts:
                raise
            _log_retry(attempt, attempts, type(error).__name__)

        delay = initial_delay_seconds * (2 ** (attempt - 1))
        if delay:
            time.sleep(delay)

    raise AssertionError("retry loop ended unexpectedly")


def quick_chat(
    prompt: str,
    *,
    system_prompt: str | None = None,
    provider: LLMProvider | None = None,
    temperature: float | None = None,
    max_tokens: int | None = None,
) -> LLMResponse:
    """Send a prompt in one function call.

    Args:
        prompt: User prompt sent to the model.
        system_prompt: Optional system instruction.
        provider: Optional configured provider; environment configuration is
            used when omitted.
        temperature: Optional sampling temperature.
        max_tokens: Optional maximum number of output tokens.

    Returns:
        Normalized LLM response.

    Raises:
        LLMConfigurationError: If the prompt is empty or configuration fails.
        httpx.HTTPError: If the API request fails.
    """

    if not prompt.strip():
        raise LLMConfigurationError("prompt must not be empty")

    messages: list[Message] = []
    if system_prompt:
        messages.append({"role": "system", "content": system_prompt})
    messages.append({"role": "user", "content": prompt})
    active_provider = provider or create_provider()
    return chat_with_retry(
        active_provider,
        messages,
        temperature=temperature,
        max_tokens=max_tokens,
    )


def _validate_messages(messages: Sequence[Message]) -> None:
    """Validate the minimum OpenAI-compatible message structure."""

    if not messages:
        raise LLMConfigurationError("messages must not be empty")
    for index, message in enumerate(messages):
        role = message.get("role")
        if not isinstance(role, str) or not role:
            raise LLMConfigurationError(f"messages[{index}].role must be a non-empty string")
        if "content" not in message:
            raise LLMConfigurationError(f"messages[{index}] must include content")


def _content_to_text(content: Any) -> str:
    """Extract text from string or OpenAI-style multipart content."""

    if content is None:
        return ""
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        parts: list[str] = []
        for item in content:
            if isinstance(item, Mapping):
                text = item.get("text")
                if isinstance(text, str):
                    parts.append(text)
        return "".join(parts)
    return str(content)


def _parse_usage(
    raw_usage: Any,
    messages: Sequence[Message],
    content: str,
) -> Usage:
    """Parse API usage or produce a local estimate."""

    if isinstance(raw_usage, Mapping):
        prompt_tokens = _nonnegative_int(raw_usage.get("prompt_tokens"))
        completion_tokens = _nonnegative_int(raw_usage.get("completion_tokens"))
        if prompt_tokens is not None and completion_tokens is not None:
            total_tokens = _nonnegative_int(raw_usage.get("total_tokens"))
            if total_tokens is None:
                total_tokens = prompt_tokens + completion_tokens
            return Usage(
                prompt_tokens=prompt_tokens,
                completion_tokens=completion_tokens,
                total_tokens=total_tokens,
            )

    prompt_tokens = estimate_message_tokens(messages)
    completion_tokens = estimate_tokens(content)
    return Usage(
        prompt_tokens=prompt_tokens,
        completion_tokens=completion_tokens,
        total_tokens=prompt_tokens + completion_tokens,
        estimated=True,
    )


def _nonnegative_int(value: Any) -> int | None:
    """Return a non-negative integer without accepting booleans."""

    if isinstance(value, int) and not isinstance(value, bool) and value >= 0:
        return value
    return None


def _first_environment_value(variable_names: Sequence[str]) -> str | None:
    """Return the first non-empty environment variable value."""

    for variable_name in variable_names:
        value = os.getenv(variable_name)
        if value and value.strip():
            return value.strip()
    return None


def _resolve_pricing(provider_name: str, model: str) -> ModelPricing | None:
    """Resolve explicit environment pricing or a known model default."""

    input_value = os.getenv("LLM_INPUT_COST_PER_MILLION")
    output_value = os.getenv("LLM_OUTPUT_COST_PER_MILLION")
    if input_value is None and output_value is None:
        return DEFAULT_PRICING.get((provider_name, model))
    if input_value is None or output_value is None:
        raise LLMConfigurationError(
            "Set both LLM_INPUT_COST_PER_MILLION and LLM_OUTPUT_COST_PER_MILLION"
        )

    try:
        pricing = ModelPricing(float(input_value), float(output_value))
    except ValueError as error:
        raise LLMConfigurationError("LLM cost variables must be valid numbers") from error
    if pricing.input_per_million < 0 or pricing.output_per_million < 0:
        raise LLMConfigurationError("LLM cost variables must not be negative")
    return pricing


def _log_retry(attempt: int, attempts: int, reason: str) -> None:
    """Log a retry without exposing prompts or credentials."""

    LOGGER.warning(
        "LLM request failed (%s); retrying after attempt %d/%d",
        reason,
        attempt,
        attempts,
    )


def _main() -> int:
    """Run a small live smoke test configured by environment variables."""

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )
    test_prompt = os.getenv(
        "LLM_TEST_PROMPT",
        "Reply with one short sentence confirming the LLM client works.",
    )
    try:
        response = quick_chat(test_prompt, max_tokens=64)
    except (LLMClientError, httpx.HTTPError) as error:
        LOGGER.error("LLM smoke test failed: %s", error)
        return 1

    LOGGER.info("LLM response: %s", response.content)
    LOGGER.info(
        "Provider=%s model=%s usage=%s estimated_cost_usd=%s",
        response.provider,
        response.model,
        response.usage,
        response.estimated_cost_usd,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(_main())
